swagger: '2.0'
info:
  title: dataToJSON RESTlet
  description: Converts various file data to JSON format
  version: 1.0.0

paths:
  /restlet:
    post:
      summary: Process a file and generate JSON output
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/RequestBody'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:

  RequestBody:
    type: object
    properties:
      fileContent:
        type: string
        description: The content of the file to be processed
      fileName:
        type: string
        description: The name of the file to be processed

  SuccessResponse:
    type: object
    properties:
      message:
        type: string
        example: "SUCCESS: Lines have been generated"
      lineJSON:
        $ref: '#/definitions/LineJSON'

  LineJSON:
    type: object
    properties:
      item:
        $ref: '#/definitions/Item'

  Item:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/LineItem'

  LineItem:
    type: object
    properties:
      line:
        type: string
        nullable: true
      item:
        $ref: '#/definitions/ItemDetails'
      description:
        type: string
        nullable: true
      quantity:
        type: number
        nullable: true
      povendor:
        $ref: '#/definitions/Vendor'
      custcol_pintel_entcode:
        type: string
        nullable: true
      custcol_pintel_listprice:
        type: number
        nullable: true
      custcol_pintel_tag1:
        type: string
        nullable: true
      custcol_pintel_tag2:
        type: string
        nullable: true
      custcol_pintel_porate:
        type: number
        nullable: true
      custcol_pintel_mancode:
        type: string
        nullable: true
      rate:
        type: number
        nullable: true
      costestimaterate:
        type: number
        nullable: true
      custcol_pintel_dealerdisc:
        type: number
        nullable: true
      custcol_pintel_custdiscount:
        type: number
        nullable: true
      custcol_pintel_optioncodedescription:
        type: string
        nullable: true

  ItemDetails:
    type: object
    properties:
      id:
        type: string
        nullable: true

  Vendor:
    type: object
    properties:
      id:
        type: string
        nullable: true

  ErrorResponse:
    type: object
    properties:
      message:
        type: string
        example: "ERROR: File type not supported"