openapi: 3.0.0
info:
  title: Orion NetSuite Services
  description: NetSuite endpoints for the BoM import tool
  version: 1.0.0
servers:
  - url: '{account}.restlets.api.netsuite.com'
    variables:
      account:
        default: td2893635
        description: Customer ID assigned by the service provider
paths:
  /*dataToJSONDomain*/app/site/hosting/restlet.nl:
    post:
      summary: Create a new file in the Netsuite file cabinet with payload and return file URL and ID
      tags:
        - dataToJSON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      parameters:
        - name: script
          in: query
          description: The script id of the RESTlet
          required: true
          schema:
            type: integer
            default: 225
        - name: deploy  
          in: query
          description: The deployment id of the RESTlet
          required: true
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/DataToJSONSuccessResponse'
        '400':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /*fileCreationDomain*/app/site/hosting/restlet.nl:
    post:
      summary: Process a file and generate JSON output
      tags:
        - bomImport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      parameters:
        - name: script
          in: query
          description: The script id of the RESTlet
          required: true
          schema:
            type: integer
            default: 292
        - name: deploy  
          in: query
          description: The deployment id of the RESTlet
          required: true
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/FileCreationResponse'
        '400':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /*getBomRecordDomain*/app/site/hosting/restlet.nl:
    post:
      summary: Create or update a BOM import record
      tags:
        - bomImport
      requestBody:
        description: Request body for creating or updating a BOM import record
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BOMImportRequest'
      parameters:
        - name: script
          in: query
          description: The script id of the RESTlet
          required: true
          schema:
            type: integer
            default: 225
        - name: deploy  
          in: query
          description: The deployment id of the RESTlet
          required: true
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BOMImportResponse'
        '400':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
components:
  schemas:
    RequestBody:
      type: object
      properties:
        fileContent:
          type: string
          description: The content of the file to be processed
        fileName:
          type: string
          description: The name of the file to be processed
          
    DataToJSONSuccessResponse:
      type: object 
      properties:
        message:
          type: string
          example: "SUCCESS: Lines have been generated"
        lineJSON:
          $ref: '#/components/schemas/LineJSON'
    
    FileCreationResponse:
      type: object
      properties:
        fileURL:
          type: string
        fileID:
          type: string
          
    BOMImportResponse:
        type: object
        properties:
          bomRecordID:
            type: string
            
    LineJSON:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/Item'
          
    Item:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
            
    LineItem:
      type: object
      properties:
        line:
          type: string
        item:
          $ref: '#/components/schemas/ItemDetails'
        description:
          type: string  
        quantity:
          type: number
        povendor:
          $ref: '#/components/schemas/Vendor'
        custcol_pintel_entcode:
          type: string
        custcol_pintel_listprice:
          type: number
        custcol_pintel_tag1:
          type: string
        custcol_pintel_tag2:
          type: string
        custcol_pintel_porate:
          type: number
        custcol_pintel_mancode:
          type: string
        rate:
          type: number
        costestimaterate:
          type: number
        custcol_pintel_dealerdisc:
          type: number
        custcol_pintel_custdiscount:
          type: number
        custcol_pintel_optioncodedescription:
          type: string
            
    ItemDetails:
      type: object
      properties:
        id:
          type: string
          
    Vendor:
      type: object 
      properties:
        id:
          type: string

    BOMImportRequest:
      type: object
      properties:
        action:
          type: string
          enum: [create, edit]
        editID:
          type: string
        custrecord_bom_import_importd_file_url:
          type: string
        custrecord_bom_import_json_importd_file:
          type: string
        custrecord_bom_import_file_import_order:
          type: integer
        custrecord_bom_import_transaction:
          type: string
        custrecord_orion_bom_intialization_ident:
          type: string
      required:
        - action
        
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: ORION_MISSING_LINES
            message:
              type: string
              example: '{"type":"error.SuiteScriptError","name":"ORION_MISSING_LINES","message":"No lines have been returned","id":null,"stack":["Error"," at Object.post (/SuiteScripts/orion/dataToJSON/orion-rs-gen-json.js:66:21)"],"cause":{"name":"ORION_MISSING_LINES","message":"No lines have been returned","notifyOff":false},"notifyOff":false,"userFacing":true}'